ALPHABET = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"

DISK_KEYS = [
    "ZBYCXDWEVFUGTHSIRJQKPLOMNA",
    "ZYXWVUTSRQPONMLKJIHGFEDCBA",
    "QWERTYUIOPASDFGHJKLZXCVBNM",
    "ZBYCXDWEVFUGTHSIRJQKPLOMNA",
    "ASDFGQWERTZXCVBYUIOPHJKLNM",
]
